services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: imei_bot
    restart: always
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - ADMIN_IDS=${ADMIN_IDS}
      - IMEI_TOKEN=${IMEI_TOKEN}
      - URL=${URL}
